"""empty message

Revision ID: cc73b20939c3
Revises: 7387a760fc51
Create Date: 2021-05-07 06:43:40.371876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc73b20939c3'
down_revision = '7387a760fc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_picture', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_picture')
    # ### end Alembic commands ###
